name: mentoria_clean_architecture
description: A Flutter project with clean architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # https://pub.dev/packages/get_it/install
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable/install
  injectable: ^1.5.3

  # https://pub.dev/packages/freezed
  freezed: ^2.1.0+1

  # https://pub.dev/packages/dio/install
  dio: ^4.0.6

  # https://pub.dev/packages/retrofit/
  retrofit: ^3.0.1+1

  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.6.0

  # https://pub.dev/packages/uuid
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints/install
  flutter_lints: ^2.0.0
  
  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.2.0

  # https://pub.dev/packages/injectable_generator
  injectable_generator: ^1.5.4

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.3.1

  # https://pub.dev/packages/retrofit_generator/
  retrofit_generator: ^4.0.3+1 
  

 


flutter:
  uses-material-design: true
